version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
      POSTGRES_HOST_AUTH_METHOD: trust # измененный параметр
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./myapp:/code
      - ./myapp/static:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - "DATABASE_URL=postgres://myuser:mypassword@db:5432/mydb"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres-data: